In [1]:
import numpy as np

In [2]:
a = np.array([[1,1,2,3],[4,5,5,6],[7,8,9,9]])

In [3]:
a

array([[1, 1, 2, 3],
       [4, 5, 5, 6],
       [7, 8, 9, 9]])

In [4]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=2)
b = svd.fit_transform(a)

In [5]:
b

array([[ 3.64908462,  1.28872246],
       [10.08671185,  0.20473492],
       [16.57622164, -0.40828119]])

In [6]:
a.dot(a.T)

array([[ 15,  37,  60],
       [ 37, 102, 167],
       [ 60, 167, 275]])

In [7]:
b.dot(b.T)

array([[ 14.9766241 ,  37.07111154,  59.96187424],
       [ 37.07111154, 101.78367242, 167.11598191],
       [ 59.96187424, 167.11598191, 274.93781743]])

In [8]:
# Suppose we have a query vector
q = np.array([[6, 4, 2, 1]])
print(q)

[[6 4 2 1]]


In [9]:
# similarities between every row in a and q
a.dot(q.T)

array([[ 17],
       [ 60],
       [101]])

In [10]:
# similarities between every row in b and transformed q
b.dot(svd.transform(q).T)

array([[ 17.06161519],
       [ 59.81256116],
       [101.1004935 ]])